version: "3.9"
services:
  sender:
    image: "kubaidullov/go-e-sender:latest"
    ports:
      - "8080:8080"
    environment:
      LISTEN: ":8080"
    networks:
      - time
  recevier:
    image: "kubaidullov/go-e-receiver:latest"
    environment:
      API_ADDR: sender:8080
      REQUESTS_FREQUENCY: 5s
    networks:
      - time

networks:
  time: